### ISSUE TITLE
redis, php ext dependency

### ISSUE THREAD

**Issue by devudopw** [blogdaren/PHPCreeper#2]
Hello

Thanks for making this php crawler.
When I playing the demo spider weather, there are some dependency issue happen.
Can you please add this to docs for requirement.

php extension: php-xml (phpQuery need this)

And for redis, how to run without redis?

**Comment by blogdaren** [comment]
1、I think it is optional for `php-xml` extension, so just use it on your demand;
2、PHPCreeper has two ways to work: `single worker mode` and `multi workers mode`: 
the former is seldomly to be used only for some simple works on one machine, here you can run the application without redis【php internal SPLQueue enabled by default】; however, the latter is frequently to be used, here we must use `redis` queue to handle  various complex  jobs, especially distributed【ah... in fact, some optimized jobs need to be done】.

so if u use the `PHPCreeper-Application`  framework, the solution is to change the work mode by chaning the configuration option  like this:  `multi_worker => false ` 【which located in `/path/to/Application/Spider/xxx/Config/main.php`】

otherwise, just write code directly like this：`PHPCreeper::$isRunAsMultiWorker = false; `

**Comment by devudopw** [comment]
Cool, please consider copy the worker mode description to docs, so others can understand better.

**Comment by blogdaren** [comment]
> Cool, please consider copy the worker mode description to docs, so others can understand better.

well, have improved the english version docs. plz see README.md for details.

**Comment by devudopw** [comment]
nice job
